const nameEl = document.querySelector("exampleInputName");
const genderMEl = document.querySelector("exampleInputGenderM");
const genderFEl = document.querySelector("exampleInputGenderF");
const birthEl = document.querySelector("exampleInputBirth");
const countryEl = document.querySelector("exampleInputCountry");
const emailEl = document.querySelector("exampleInputEmail1");
const passwordEl = document.querySelector("exampleInputPassword");
const photoEl = document.querySelector("exampleInputFile");
const adminEl = document.querySelector("input[name=admin]");
